### ISSUE TITLE
#10 line-heightで行の高さを調整しようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#10]
[#10 line-heightで行の高さを調整しよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51210)を進める

**Comment by Ju-miura** [comment]
OKです。
単位が増えてきたので順に覚えていきましょう（既に知ってるかもしれないけど）。
