### ISSUE TITLE
#11 単位無しでline-heightを指定しようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#11]
[#11 単位無しでline-heightを指定しよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51211)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
@Shirahamah 
ついでに書くと、完了しているとこへのリンクがあると、より親切かなと感じました。
以下のような感じ

https://github.com/Shirahamah/dotinstall_basic_css#11-%E5%8D%98%E4%BD%8D%E3%81%AA%E3%81%97%E3%81%A7line-height%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%82%88%E3%81%86

**Comment by sugasaki-atsushi** [comment]
Closeします
