### ISSUE TITLE
#12 vertical-alignで位置を調整しようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#12]
[#12 vertical-alignで位置を調整しよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51212)をやる

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
ここで何をやったのかが、↓を見てもコメントを見てもわからなかったので、
https://github.com/Shirahamah/dotinstall_basic_css#12-vertical-align%E3%81%A7%E4%BD%8D%E7%BD%AE%E3%82%92%E8%AA%BF%E6%95%B4%E3%81%97%E3%82%88%E3%81%86

「完了しています」だけじゃなくて、やった事も書いて欲しいです。
12の場合だと、おそらく以下みたいな感じだと思う

- 画像を上寄せにした。（vertical-align: top;）
- Pタグの幅を5に設定

**Comment by sugasaki-atsushi** [comment]
ソース見たけど、baseline はどこにも登場してなくてOK？

**Comment by Shirahamah** [comment]
了解です。やったことまで書くようにします。
baselineは文字が配置されるときの基準として出てきたので、登場していなくて大丈夫です・

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
