### ISSUE TITLE
#14 HSLAを使った色の表現方法を覚えようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#14]
[#14 HSLAを使った色の表現方法を覚えよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51214)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
