### ISSUE TITLE
#16 一括指定プロパティを使ってみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#16]
[#16 一括指定プロパティを使ってみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51216)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
