### ISSUE TITLE
#22 marginで外側の余白をつけようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#22]
[#22 marginで外側の余白をつけよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51222)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
