### ISSUE TITLE
#24 displayプロパティについて理解しようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#24]
[#24 displayプロパティについて理解しよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51224)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
