### ISSUE TITLE
#25 displayプロパティを操作してみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#25]
[#25 displayプロパティを操作してみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51225)を進める

**Comment by Shirahamah** [comment]
完了しています。

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
