### ISSUE TITLE
#26 positionで要素の位置を変えようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#26]
[#26 positionで要素の位置を変えよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51226)を進める

**Comment by Shirahamah** [comment]
完了しました。
https://github.com/Shirahamah/dotinstall_basic_css#26-position%E3%81%A7%E8%A6%81%E7%B4%A0%E3%81%AE%E4%BD%8D%E7%BD%AE%E3%82%92%E5%A4%89%E3%81%88%E3%82%88%E3%81%86

- static,relative,fixedの動作確認 (top,leftを30px移動)
- fixedのとき、固定配置されていることの確認

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
