### ISSUE TITLE
#27 要素を絶対配置してみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#27]
[#27 要素を絶対配置してみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51227)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#27-%E8%A6%81%E7%B4%A0%E3%82%92%E7%B5%B6%E5%AF%BE%E9%85%8D%E7%BD%AE%E3%81%97%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

- box2にposition: relative;を指定
- box3にposition: absolute;を指定
- top,right(left)を指定し、配置を移動

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
