### ISSUE TITLE
#28 z-indexで重なり順を操作しようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#28]
[#28 z-indexで重なり順を操作しよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51228)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#28-z-index%E3%81%A7%E9%87%8D%E3%81%AA%E3%82%8A%E9%A0%86%E3%82%92%E6%93%8D%E4%BD%9C%E3%81%97%E3%82%88%E3%81%86

- box1,box2,box3をすべて絶対配置に(position: absolute;)
- box2,box3を少しずらして配置(top,left)
- z-indexを指定

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
