### ISSUE TITLE
#29 box-sizingを使ってみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#29]
[#29 box-sizingを使ってみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51229)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#29-box-sizing%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

- box2にborderを設定(10px solid blue)
- box2のサイズが他boxとずれることを確認したのち、box2にbox-sizing: border-box;を指定

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
