### ISSUE TITLE
#30 calcで単位が違う計算をしてみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#30]
[#30 calcで単位が違う計算をしてみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51230)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#30-calc%E3%81%A7%E5%8D%98%E4%BD%8D%E3%81%8C%E9%81%95%E3%81%86%E8%A8%88%E7%AE%97%E3%82%92%E3%81%97%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86-0250

- box2にmargin: auto;,box3にmargin-left: auto;を指定し、boxを右、中、左に配置
- それぞれのbox間隔が20pxになるように配置する(箱の幅をxとすると、3x+40px=100%)
- width に calc((100% - 40px) / 3 ) を指定

**Comment by sugasaki-atsushi** [comment]
OKです。Closeします
