### ISSUE TITLE
#31 要素に影をつけてみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#31]
[#31 要素に影をつけてみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51231)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#31-%E8%A6%81%E7%B4%A0%E3%81%AB%E5%BD%B1%E3%82%92%E3%81%A4%E3%81%91%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

- box1にx方向10px、y方向5pxの影を付ける   (box-shadow: 10px 5px rgba(0, 0, 0, 0.3);)
- box2にbox1と同じ影を付け、影をぼかす     (box-shadow: 10px 5px 3px rgba(0, 0, 0, 0.3);)
- box3にbox2と同じ影を付け、影を拡大する (box-shadow: 10px 5px 3px 10px rgba(0, 0, 0, 0.3);
- textもbox同様に影を付ける

**Comment by sugasaki-atsushi** [comment]
@Shirahamah 
ちなみにこれIEで表示してみてください

**Comment by Shirahamah** [comment]
表示確認しましたが、特に問題ありませんでした。

**Comment by sugasaki-atsushi** [comment]
りょーかい
口頭でも伝えたけど、時々IEでもチェックしてみてね。
