### ISSUE TITLE
#32 背景のスタイリングをしていこうをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#32]
[#32 背景のスタイリングをしていこう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51232)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#32-%E8%83%8C%E6%99%AF%E3%81%AE%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AA%E3%83%B3%E3%82%B0%E3%82%92%E3%81%97%E3%81%A6%E3%81%84%E3%81%93%E3%81%86

- 高さ、背景色、背景画像、画像サイズ、画像位置を指定(height,background-color,background-image,background-size,background-position)
- 上記で指定したものを一括指定で指定

**Comment by sugasaki-atsushi** [comment]
@Shirahamah
これもIEで表示してみてください

**Comment by Shirahamah** [comment]
@sugasaki-atsushi 
表示確認しましたが、特に問題ありませんでした。

**Comment by sugasaki-atsushi** [comment]
りょーかい
口頭でも伝えたけど、時々IEでもチェックしてみてね。
