### ISSUE TITLE
#33 floatを使ってみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#33]
[#33 floatを使ってみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51233)を進める

**Comment by Shirahamah** [comment]
完了しています。
https://github.com/Shirahamah/dotinstall_basic_css#33-float%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

- pタグの中にimgを配置
- imgにfloat: right;を指定し、画像を右に寄せる
- h2にclear: right;を指定し、floatさせた要素の下に配置（左にfloatさせた場合はclear: left;、両方floatさせた場合はclear: both;）

**Comment by sugasaki-atsushi** [comment]
OKです。よくがんばりましたね。
