### ISSUE TITLE
#07 デベロッパーツールを使ってみようをやる

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css#7]
[#07 デベロッパーツールを使ってみよう | 詳解CSS 基礎文法編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_styles_v2/51207)を進める

**Comment by Ju-miura** [comment]
OKです。
使いこなせると色々な情報がわかるので、ちょっとずつ色々試していってみましょう。
